### ISSUE TITLE
Barrels not dropping themselves upon breaking

### ISSUE THREAD

**Issue by pommellie** [pnk2u/More-Barrel-Variants#2]
Using the mod and noticed that whenever I break a variant barrel (notably the Oak Barrel, as that is the one I am using) it doesn't drop itself when using an axe.

I have tested this with the Spruce Barrel, and it drops itself just fine. I do not know about the other barrel as I have not crafted them in my game.

I am playing MC 1.21 using Fabric 0.16.0, is this helps any.

**Comment by pnk2u** [comment]
Thanks again so much for reporting this issue. I just uploaded version 1.5.8 to Modrinth (and Curseforge, but there it might need a moment to become available).
And yes, mentioning that it was 1.21 helped me figure out this issue more quickly as it did only affect that version. I believe 1.5.8 resolves the problem. If that fixes it, feel free to close this issue. (:

**Comment by pommellie** [comment]
It does work now! Thank you so much!
