### ISSUE TITLE
Pale Variant of Barrel has no recipe.

### ISSUE THREAD

**Issue by zombiethoughts** [pnk2u/More-Barrel-Variants#7]
The Pale Barrel, while showing up in REI, does not have a recipe. So it's only obtainable through creative.

Using release 1.7.4 for 1.21.4

Thank you for your fantastic work!

**Comment by pnk2u** [comment]
Hey, thanks for the kind words and for the report, fixed it in version 1.7.5 that I just uploaded. Hope that resolves the issue. (:

**Comment by zombiethoughts** [comment]
You are amazing! Just made some coffee and you had the update done! Tested and works great! Closing this one!
