### ISSUE TITLE
Pale Oak Barrel doesn't drop when broken.

### ISSUE THREAD

**Issue by zombiethoughts** [pnk2u/More-Barrel-Variants#8]
ver 1.7.5

I don't think there is a tool associated with the Pale Oak Barrel, so it doesn't drop when broken. It just breaks.

Thank you again!

**Comment by pnk2u** [comment]
Thanks again for the report, should all be fixed in 1.7.6. Thank you for your patience. (:

**Comment by zombiethoughts** [comment]
Thank you! Tested and works!
